name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-neptune-experimental:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: pip install poetry poetry-dynamic-versioning

      - name: Build package
        run: poetry build

      - uses: actions/upload-artifact@v4
        with:
          name: neptune-experimental-package
          path: dist/

  publish-neptune-experimental:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: neptune-experimental-package
          path: dist/

      - name: Uploading to test PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
         user: __token__
         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
         repository_url: https://test.pypi.org/legacy/

      - name: Uploading to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
