name: unit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 75
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"] #, "3.11"]
        os: [ubuntu] #, windows]
#        include:
#          - python-version: "3.7.16"
#            os: macos
#          - python-version: "3.11"
#            os: macos

    name: 'test (${{ matrix.os }} - py${{ matrix.python-version }})'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Run tests
        uses: ./.github/actions/test-unit
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}
          report_job: 'test (${{ matrix.os }} - py${{ matrix.python-version }})'
